// frontend/src/views/CreateTaskView.vue
<script setup lang="ts">
// Phase 1 待实现：任务创建表单 + TipTap 富文本 + 文件上传
</script>

<template>
  <div class="max-w-3xl mx-auto px-6 py-8">
    <h1 class="text-2xl font-semibold text-gray-900">发布任务</h1>
    <p class="text-sm text-gray-500 mt-1">两种模式：招标 或 直接指名</p>

    <div class="card mt-6 text-center py-12 text-gray-500">
      <p>任务创建表单</p>
      <p class="text-xs mt-2">Phase 1 待实现：招标表单 + 直接指名表单 + TipTap 富文本 + 文件上传</p>
    </div>
  </div>
</template>

// frontend/src/views/CreateTaskView.tsx
import { Card, CardContent } from '@/components/ui/card'

export function CreateTaskView() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-8">
      <h1 className="text-2xl font-semibold text-foreground">发布任务</h1>
      <p className="mt-1 text-sm text-muted-foreground">两种模式：招标 或 直接指名</p>
      <Card className="mt-6">
        <CardContent className="py-12 text-center text-muted-foreground">
          <p>任务创建表单</p>
          <p className="mt-2 text-xs">Phase 1 待实现：招标表单 + 直接指名表单 + TipTap 富文本 + 文件上传</p>
        </CardContent>
      </Card>
    </div>
  )
}
